obj-$(CONFIG_BKSV) += bksv_gpio.o
obj-$(CONFIG_BKSV) += bksv_adc.o 
obj-$(CONFIG_BKSV) += bksv_dac.o 
obj-$(CONFIG_BKSV) += bksv_timer.o 
obj-$(CONFIG_BKSV) += bksv_tcpci.o 
obj-$(CONFIG_BKSV) += bksv_lightring.o
